# Generated by Django 2.2.2 on 2019-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('who', models.TextField(verbose_name='who created')),
                ('request_body', models.TextField(null=True, verbose_name='request body')),
            ],
        ),
    ]
