# Generated by Django 2.2.2 on 2019-06-20 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtbUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='user id')),
                ('name', models.TextField(null=True, verbose_name='name')),
                ('username', models.TextField(null=True, verbose_name='user name')),
                ('language', models.CharField(max_length=10, null=True, verbose_name='language')),
                ('avatar_url', models.TextField(null=True, verbose_name='avatar url')),
                ('full_avatar_url', models.TextField(null=True, verbose_name='full avatar url')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='TtbPrevStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=64, unique=True, verbose_name='index')),
                ('update', models.TextField(verbose_name='user update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djh_app.TtbUser', verbose_name='user')),
            ],
        ),
    ]
